// SPDX-License-Identifier: MPL-2.0

// openapigen generates internal/provider/openapidocs from the vendored SnapCD OpenAPI
// document (schemas/openapi.yaml): attribute description constants from the DTO schemas,
// and per-endpoint "Required permissions" markdown from the x-snapcd-permissions
// operation extensions. The spec is the source of truth; refresh it with `make sync-openapi`.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	spec := flag.String("spec", "../schemas/openapi.yaml", "path to the vendored OpenAPI document")
	out := flag.String("out", "../internal/provider/openapidocs", "output package directory")
	flag.Parse()

	raw, err := os.ReadFile(*spec)
	if err != nil {
		fatal(err)
	}

	var doc map[string]any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		fatal(err)
	}

	if err := os.MkdirAll(*out, 0o755); err != nil {
		fatal(err)
	}
	enums := collectEnums(doc)
	write(filepath.Join(*out, "descriptions_gen.go"), emitDescriptions(doc, enums))
	write(filepath.Join(*out, "permissions_gen.go"), emitPermissions(doc))
	write(filepath.Join(*out, "enums_gen.go"), emitEnums(enums))
	fmt.Println("openapigen: wrote descriptions_gen.go, permissions_gen.go, enums_gen.go")
}

func write(path, source string) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fatal(fmt.Errorf("formatting %s: %w", path, err))
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "openapigen:", err)
	os.Exit(1)
}

func header(sb *strings.Builder) {
	sb.WriteString("// Code generated by openapigen from schemas/openapi.yaml. DO NOT EDIT.\n")
	sb.WriteString("//\n")
	sb.WriteString("// Refresh with `make sync` (or `make sync-local`) followed by `make generate`.\n\n")
	sb.WriteString("package openapidocs\n\n")
}

// collectEnums returns every enum schema's string values (the `null` entry of nullable
// enums is not a string and drops out).
func collectEnums(doc map[string]any) map[string][]string {
	enums := map[string][]string{}
	schemas := dig(doc, "components", "schemas")
	for _, schemaName := range sortedKeys(schemas) {
		if values := stringList(dig(schemas, schemaName)["enum"]); len(values) > 0 {
			enums[schemaName] = values
		}
	}
	return enums
}

// emitEnums renders one exported values slice per enum schema, for use in
// stringvalidator.OneOf(openapidocs.XValues...).
func emitEnums(enums map[string][]string) string {
	var sb strings.Builder
	header(&sb)
	for _, name := range sortedKeys(anyMap(enums)) {
		quoted := make([]string, len(enums[name]))
		for i, v := range enums[name] {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		sb.WriteString(fmt.Sprintf("var %sValues = []string{%s}\n\n", name, strings.Join(quoted, ", ")))
	}
	return sb.String()
}

var refEnumRe = regexp.MustCompile(`^#/components/schemas/(\w+)$`)

// enumRef resolves the enum schema a property references, either directly ($ref with a
// sibling description) or through the nullable oneOf shape.
func enumRef(property map[string]any, enums map[string][]string) string {
	candidates := []any{property["$ref"]}
	for _, branch := range asList(property["oneOf"]) {
		if b, ok := branch.(map[string]any); ok {
			candidates = append(candidates, b["$ref"])
		}
	}
	for _, candidate := range candidates {
		if ref, ok := candidate.(string); ok {
			if m := refEnumRe.FindStringSubmatch(ref); m != nil {
				if _, isEnum := enums[m[1]]; isEnum {
					return m[1]
				}
			}
		}
	}
	return ""
}

// emitDescriptions renders one exported constant per documented schema property, named
// {Schema}_{PascalProperty}. Enum-typed properties get a generated "Must be one of …"
// sentence appended, unless the description already lists its values (hand-written
// sentences stay authoritative where the provider intentionally restricts the set).
func emitDescriptions(doc map[string]any, enums map[string][]string) string {
	var sb strings.Builder
	header(&sb)
	sb.WriteString("const (\n")

	schemas := dig(doc, "components", "schemas")
	for _, schemaName := range sortedKeys(schemas) {
		properties := dig(schemas, schemaName, "properties")
		if properties == nil {
			continue
		}
		wrote := false
		for _, propName := range sortedKeys(properties) {
			property := dig(properties, propName)
			description, _ := property["description"].(string)
			if description == "" {
				continue
			}
			if enumName := enumRef(property, enums); enumName != "" &&
				!strings.Contains(description, "Must be one of") &&
				!strings.Contains(description, "Valid values") {
				description = strings.TrimRight(description, " ")
				if !strings.HasSuffix(description, ".") {
					description += "."
				}
				description += " Must be one of '" + strings.Join(enums[enumName], "', '") + "'."
			}
			if !wrote {
				sb.WriteString(fmt.Sprintf("\n\t// %s\n", schemaName))
				wrote = true
			}
			sb.WriteString(fmt.Sprintf("\t%s_%s = %q\n", schemaName, pascal(propName), description))
		}
	}

	sb.WriteString(")\n")
	return sb.String()
}

var pathFamilyRe = regexp.MustCompile(`^/api/\{organizationId\}/([A-Za-z]+)`)

var lifecycleVerbs = []string{"Create", "Read", "Update", "Delete"}

// emitPermissions renders per-endpoint-family "Required permissions" markdown from
// x-snapcd-permissions: ResourcePermissions lists the roles that grant the resource's full
// lifecycle (the intersection across its Create/Read/Update/Delete maps), DataSourcePermissions
// the Read roles. The blocks are embedded into schema MarkdownDescriptions, which tfplugindocs
// splits on " --- " — the generated text must never contain that separator.
func emitPermissions(doc map[string]any) string {
	families := map[string]map[string][]string{}
	reverseRead := map[string][]string{}

	paths := dig(doc, "paths")
	for _, path := range sortedKeys(paths) {
		m := pathFamilyRe.FindStringSubmatch(path)
		if m == nil {
			continue
		}
		family := m[1]
		operations := dig(paths, path)
		for _, method := range sortedKeys(operations) {
			perms := dig(operations, method, "x-snapcd-permissions")
			if perms == nil {
				continue
			}
			verb, _ := perms["verb"].(string)
			roles := stringList(perms["anyOf"])
			if verb == "" || len(roles) == 0 {
				continue
			}
			if families[family] == nil {
				families[family] = map[string][]string{}
			}
			if existing, ok := families[family][verb]; ok && strings.Join(existing, ",") != strings.Join(roles, ",") {
				fmt.Fprintf(os.Stderr, "openapigen: warning: %s %s has conflicting permission maps across operations; keeping the first\n", family, verb)
				continue
			}
			families[family][verb] = roles
			if verb == "Read" {
				reverseRead[family] = stringList(perms["reverseInheritedAnyOf"])
			}
		}
	}

	var sb strings.Builder
	header(&sb)

	sb.WriteString("// ResourcePermissions maps an API endpoint family to a markdown line listing the\n")
	sb.WriteString("// roles that grant the resource's full lifecycle (the intersection across its\n")
	sb.WriteString("// Create/Read/Update/Delete permission maps). Append to a resource's MarkdownDescription.\n")
	sb.WriteString("var ResourcePermissions = map[string]string{\n")
	for _, family := range sortedKeys(anyMap(families)) {
		roles := lifecycleIntersection(families[family])
		if len(roles) == 0 {
			fmt.Fprintf(os.Stderr, "openapigen: warning: %s has an empty lifecycle permission intersection; skipping\n", family)
			continue
		}
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", family, permissionLine(roles, nil)))
	}
	sb.WriteString("}\n\n")

	sb.WriteString("// DataSourcePermissions is the Read-only variant for data sources.\n")
	sb.WriteString("var DataSourcePermissions = map[string]string{\n")
	for _, family := range sortedKeys(anyMap(families)) {
		if roles, ok := families[family]["Read"]; ok {
			sb.WriteString(fmt.Sprintf("\t%q: %q,\n", family, permissionLine(roles, reverseRead[family])))
		}
	}
	sb.WriteString("}\n")
	return sb.String()
}

// lifecycleIntersection returns the roles present in every documented lifecycle verb, in the
// order of the Read map (the broadest, with stable dimension ordering).
func lifecycleIntersection(verbs map[string][]string) []string {
	base := verbs["Read"]
	if base == nil {
		for _, verb := range lifecycleVerbs {
			if verbs[verb] != nil {
				base = verbs[verb]
				break
			}
		}
	}

	var out []string
	for _, role := range base {
		inAll := true
		for _, verb := range lifecycleVerbs {
			roles, ok := verbs[verb]
			if !ok {
				continue
			}
			found := false
			for _, r := range roles {
				if r == role {
					found = true
					break
				}
			}
			if !found {
				inAll = false
				break
			}
		}
		if inAll {
			out = append(out, role)
		}
	}
	return out
}

func permissionLine(roles, reverse []string) string {
	quoted := make([]string, len(roles))
	for i, role := range roles {
		quoted[i] = "`" + role + "`"
	}
	line := "Any of: " + strings.Join(quoted, ", ")
	for _, dim := range reverse {
		line += fmt.Sprintf(", or *any* role on a contained %s (`%s`)", strings.TrimSuffix(dim, ".*"), dim)
	}
	return line
}

// ---- helpers

func dig(node any, keys ...string) map[string]any {
	current, ok := node.(map[string]any)
	if !ok {
		return nil
	}
	for _, key := range keys {
		current, ok = current[key].(map[string]any)
		if !ok {
			return nil
		}
	}
	return current
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func anyMap[V any](m map[string]V) map[string]any {
	out := make(map[string]any, len(m))
	for k := range m {
		out[k] = struct{}{}
	}
	return out
}

func asList(node any) []any {
	items, _ := node.([]any)
	return items
}

func stringList(node any) []string {
	items, ok := node.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func pascal(camel string) string {
	if camel == "" {
		return camel
	}
	return strings.ToUpper(camel[:1]) + camel[1:]
}
