// Code generated by openapigen from schemas/openapi.yaml. DO NOT EDIT.
//
// Refresh with `make sync` (or `make sync-local`) followed by `make generate`.

package openapidocs

var AgentRoleValues = []string{"Owner", "Contributor", "Reader", "IdentityAccessManager"}

var CancellationTypeValues = []string{"AfterCurrent", "ImmediateGraceful", "ImmediateKill"}

var ColorTargetTypeValues = []string{"Stack", "Namespace", "Module"}

var DefinitionInputTypeValues = []string{"StackId", "StackName", "NamespaceId", "NamespaceName", "ModuleId", "ModuleName", "SourceRevision", "SourceUrl", "SourceSubdirectory"}

var DiagnosisCategoryValues = []string{"Unknown", "ProviderTransient", "ProviderAuth", "ModuleCode", "Configuration", "StateDrift", "Dependency", "Quota", "DeclinedApproval", "ExternalMutation"}

var FavoriteTargetTypeValues = []string{"Stack", "Namespace", "Module"}

var GroupMemberDiscriminatorValues = []string{"Base", "User", "ServicePrincipal", "Group"}

var HookPhaseValues = []string{"Before", "After"}

var HookTaskValues = []string{"Init", "Plan", "PlanDestroy", "Apply", "Destroy", "Output", "Validate"}

var InputKindValues = []string{"Param", "EnvVar"}

var InputTypeValues = []string{"String", "NotString"}

var IntegrationRoleValues = []string{"Owner", "Contributor", "Reader", "IdentityAccessManager"}

var IntegrationSupplyScopeValues = []string{"Stack", "Namespace", "Module"}

var IntegrationTriggerValues = []string{"JobSucceeded", "JobFailed", "JobAwaitingApproval", "JobApproved", "JobDeclined", "JobCancelled", "MissionStarted", "MissionMilestoneReported", "MissionCompleted", "MissionFaulted"}

var IntegrationTypeValues = []string{"Slack"}

var MissionStatusValues = []string{"Pending", "WaitingForAgent", "BlockedAgentNotAssigned", "Running", "AwaitingReconnect", "Succeeded", "Failed", "Cancelled", "TimedOut"}

var MissionTypeValues = []string{"AutoDiagnose", "ApprovalRecommend", "SummarizeJob", "AutoFix"}

var ModuleRoleValues = []string{"Owner", "Contributor", "Reader", "IdentityAccessManager", "JobManager"}

var NamespaceInputUsageModeValues = []string{"UseIfSelected", "UseByDefault"}

var NamespaceRoleValues = []string{"Owner", "Contributor", "Reader", "ModuleCreator", "IdentityAccessManager", "JobManager"}

var NamespaceTriggerBehaviourValues = []string{"DoNotTrigger", "TriggerAllImmediately"}

var OrganizationRoleValues = []string{"Owner", "Contributor", "Reader", "StackCreator", "IdentityAccessManager", "JobManager", "SourceChangeNotifier", "SubscriptionManager", "StackContributor", "StackReader", "RunnerCreator", "RunnerContributor", "RunnerReader", "AgentCreator", "AgentContributor", "AgentReader", "SourceRefresherPreselectionCreator", "SourceRefresherPreselectionContributor", "SourceRefresherPreselectionReader", "IntegrationCreator", "IntegrationContributor", "IntegrationReader", "StateStoreCreator", "StateStoreContributor", "StateStoreReader"}

var PolicyEvaluateOnValues = []string{"ApplyAndDestroy", "ApplyOnly", "DestroyOnly"}

var PrincipalDiscriminatorValues = []string{"User", "ServicePrincipal"}

var PulumiArrayFlagValues = []string{"PolicyPack", "PolicyPackConfig", "AttachDebugger", "Target", "Replace", "Exclude", "TargetReplace", "Config"}

var PulumiCommandTaskValues = []string{"Init", "Plan", "Apply", "Destroy", "Output"}

var PulumiFlagValues = []string{"CloudUrl", "LoginLocal", "LoginCloud", "DefaultOrg", "Insecure", "OidcExpiration", "OidcOrg", "OidcTeam", "OidcToken", "OidcUser", "StackName", "SecretsProvider", "CreateStack", "ConfigFile", "Debug", "Diff", "ExpectNoChanges", "Json", "Message", "Parallel", "Refresh", "RunProgram", "ShowConfig", "ShowFullOutput", "ShowReads", "ShowReplacementSteps", "ShowSames", "ShowSecrets", "SuppressOutputs", "SuppressProgress", "TargetDependents", "ExcludeDependents", "Neo", "ImportFile", "ContinueOnError", "SkipPreview", "Strict", "ExcludeProtected", "Remove", "Shell", "Color", "Verbose", "Emoji"}

var PulumiPolicyRuntimeValues = []string{"Python", "NodeJS"}

var RoleAssignmentPrincipalDiscriminatorValues = []string{"Base", "User", "ServicePrincipal", "Group"}

var RunnerRoleValues = []string{"Owner", "Contributor", "Reader", "IdentityAccessManager"}

var SourceRevisionTypeValues = []string{"Default", "SemanticVersionRange"}

var SourceTypeValues = []string{"Git", "Registry", "S3", "Http", "Https", "Gcs", "Mercurial", "Unknown"}

var StackRoleValues = []string{"Owner", "Contributor", "Reader", "NamespaceCreator", "IdentityAccessManager", "JobManager"}

var StackTriggerBehaviourValues = []string{"DoNotTrigger", "TriggerAllImmediately"}

var StateManagementEngineValues = []string{"OpenTofu", "Terraform", "Pulumi"}

var StateStoreRoleValues = []string{"Owner", "Contributor", "Reader", "IdentityAccessManager"}

var TerraformArrayFlagValues = []string{"Target", "Replace", "Exclude", "Var", "BackendConfig"}

var TerraformCommandTaskValues = []string{"Init", "Plan", "Apply", "Destroy", "Output"}

var TerraformFlagValues = []string{"ForceCopy", "FromModule", "GetPlugins", "LockTimeout", "Lockfile", "MigrateState", "Plugin", "Reconfigure", "TestDirectory", "Upgrade", "CompactWarnings", "Concurrency", "Lock", "NoColor", "Parallelism", "Refresh", "RefreshOnly", "DetailedExitcode", "GenerateConfigOut", "CreateBeforeDestroy", "Raw"}

var WaitForApplyDependenciesValues = []string{"Always", "Never", "OnFirstApply"}

var WaitForDestroyDependenciesValues = []string{"Always", "Never"}
